# docker build -f Dockerfile.nest -t azamara/drone-examples-nest:0.0.1
# docker tag azamara/drone-examples-nest:0.0.1 azamara/drone-examples-nest:latest

FROM node:10.19.0

RUN apt-get install -y curl

COPY packages/nest/package.json /service/packages/nest/package.json

RUN cd /service/packages/nest; npm install

RUN npm install

RUN npm run build

WORKDIR /service/packages/nest/dist

EXPOSE 3000

ENTRYPOINT ["node", "main.js"]
